site_name: "GCC Photo Vote"
# You can include inline HTML by wrapping the whole string in single quotes so inner double quotes are preserved.
site_title: 'GCC Photography<span class="text-xs align-super">2025</span>'
submission_forms_url: "https://forms.gle/your-form-id-submit"
voting_forms_url: "https://forms.gle/your-form-id-voting"
deadlines:
  submit_open: "2025-08-21 14:30:00" 
  submit_close: "2025-08-21 16:00:00" 
  voting_open: "2025-08-25 11:30:00"
  voting_close: "2025-08-25 19:00:00"
  # Optional: set the time when the results link/button should appear
  # If not set and show_results is true, results will show immediately after voting ends
  # If show_results is false, nothing related to results will be shown
  results: "2025-09-01 15:30:00"
show_countdown: all # voting, submission, all or none
show_gallery: [ voting, results ] #voting, submission, all or none. Set to none to hide carousel and gallery cards. 
show_voting: true # Set to false to hide the vote button
show_results: true # Set to true to show results button after voting ends
show_features: submission # Controls visibility of the features section. Options: all, submission, voting, none.
show_team_data: results # Controls when real team names are shown: all, none, submission, voting, results, or an array of phases. Use 'none' to always anonymize. Deprecated: hide_team_data.
home_title: 'GCC Photography<span class="text-xs align-super">2025</span>'
home_description_submission: 'Submit your best photos and showcase your talent.'
home_description_voting: 'Explore submissions, vote for your favorites, and celebrate creativity. <strong>Scroll down</strong> to view the gallery when the voting phase is open.'
home_description_results: 'Thank you for participating! Check out the results below when the results phase is open.'
show_date: all # submission, voting, all, none. Controls whether a phase date line appears.
features:
  - title: 'Eligi<span class="text-xs align-super">bility</span>'
    description: "Open to all students of Gopalan College of Commerce. Submit original photographs only."
  - title: 'Cate<span class="text-xs align-super">gories</span>'
    description: "Nature, Portrait, Street Photography, Abstract, and Creative categories available."
  - title: 'Prizes<span class="text-xs align-super">& Awards</span>'
    description: "Winners will receive certificates and exciting prizes. Exhibition of winning entries."
footer:
  text: "© 2025 (BCA) NeoTech Club, GCC"
  mono_link: "https://mono.layogtima.com/"
